[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld", 
    "-Cforce-frame-pointers=yes"
]